spring.application.name=recommendation-service
server.port=8083
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:${eureka.client.serviceUrl.defaultZone:http://localhost:8080/eureka/}}}
eureka.client.service-url.default-zone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:${eureka.client.serviceUrl.defaultZone:http://localhost:8080/eureka/}}}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME:localhost}
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=180
            




# Resilience4j Circuit Breaker Configuration
resilience4j.circuitbreaker.instances.recommendationService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.recommendationService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.recommendationService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.recommendationService.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.recommendationService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.recommendationService.automaticTransitionFromOpenToHalfOpenEnabled=true

# Actuator Endpoints Configuration
management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always

# Aspect Order (CircuitBreaker outermost -> catches all exceptions to trigger fallback)
resilience4j.circuitbreaker.circuitBreakerAspectOrder=1
resilience4j.ratelimiter.rateLimiterAspectOrder=2
resilience4j.retry.retryAspectOrder=4
resilience4j.timelimiter.timeLimiterAspectOrder=5

# Retry Configuration
resilience4j.retry.instances.recommendationService.maxAttempts=3
resilience4j.retry.instances.recommendationService.waitDuration=1s

# TimeLimiter Configuration
resilience4j.timelimiter.instances.recommendationService.timeoutDuration=2s
resilience4j.timelimiter.instances.recommendationService.cancelRunningFuture=true

# RateLimiter Configuration
resilience4j.ratelimiter.instances.recommendationService.limitForPeriod=5
resilience4j.ratelimiter.instances.recommendationService.limitRefreshPeriod=1s
resilience4j.ratelimiter.instances.recommendationService.timeoutDuration=0

# Bulkhead Configuration
resilience4j.bulkhead.instances.recommendationService.maxConcurrentCalls=1
resilience4j.bulkhead.instances.recommendationService.maxWaitDuration=0

# Distributed Tracing Configuration
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
