spring.application.name=api-gateway
server.port=8084

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:${eureka.client.serviceUrl.defaultZone:http://localhost:8080/eureka/}}}
eureka.client.service-url.default-zone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:${eureka.client.serviceUrl.defaultZone:http://localhost:8080/eureka/}}}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME:localhost}
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=180

# Gateway Routes with Eureka Discovery & StripPrefix
spring.cloud.gateway.routes[0].id=product-service
spring.cloud.gateway.routes[0].uri=${PRODUCT_SERVICE_URL:lb://PRODUCT-SERVICE}
spring.cloud.gateway.routes[0].predicates[0]=Path=/product-service/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=inventory-service
spring.cloud.gateway.routes[1].uri=${INVENTORY_SERVICE_URL:lb://INVENTORY-SERVICE}
spring.cloud.gateway.routes[1].predicates[0]=Path=/inventory-service/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[2].id=recommendation-service
spring.cloud.gateway.routes[2].uri=${RECOMMENDATION_SERVICE_URL:lb://RECOMMENDATION-SERVICE}
spring.cloud.gateway.routes[2].predicates[0]=Path=/recommendation-service/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

# Distributed Tracing Configuration
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans



